// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UserChatService.Infrastructure;

#nullable disable

namespace UserChatService.Infrastructure.Migrations
{
    [DbContext(typeof(UserChatDbContext))]
    [Migration("20240818034104_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("UserChatService.Domain.Entities.UserChat.UserDialog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("User_Dialog", (string)null);
                });

            modelBuilder.Entity("UserChatService.Domain.Entities.UserChat.UserDialogMessage", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime(6)");

                    b.Property<long>("FromUserId")
                        .HasColumnType("bigint");

                    b.Property<bool>("FromUser_Deleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("MarkRead")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("MessageType")
                        .HasColumnType("int");

                    b.Property<string>("PostMessages")
                        .HasColumnType("longtext");

                    b.Property<bool>("RetractMessage")
                        .HasColumnType("tinyint(1)");

                    b.Property<long>("ToUserId")
                        .HasColumnType("bigint");

                    b.Property<bool>("ToUser_Deleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<long>("UserDialogId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("UserDialogId", "ToUserId", "MarkRead");

                    b.ToTable("User_DialogMessage", (string)null);
                });

            modelBuilder.Entity("UserChatService.Domain.Entities.UserChat.UserDialogToUser", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DeletionTime")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("ToUserAvatar")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<long>("ToUserId")
                        .HasColumnType("bigint");

                    b.Property<string>("ToUserName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("TopTime")
                        .HasColumnType("datetime(6)");

                    b.Property<long>("UserDialogId")
                        .HasColumnType("bigint");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("ToUserId", "UserId");

                    b.HasIndex("UserId", "UserDialogId");

                    b.ToTable("User_DialogToUser", (string)null);
                });

            modelBuilder.Entity("UserChatService.Domain.Entities.UserChat.UserGroups", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<long>("AdminId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Introduce")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Notice")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("User_Groups", (string)null);
                });

            modelBuilder.Entity("UserChatService.Domain.Entities.UserChat.UserGroupsMessage", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("FromUserAvatar")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<long>("FromUserId")
                        .HasColumnType("bigint");

                    b.Property<string>("FromUserName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("MessageType")
                        .HasColumnType("int");

                    b.Property<string>("PostMessages")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("RetractMessage")
                        .HasColumnType("tinyint(1)");

                    b.Property<long>("UserGroupsId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("FromUserId");

                    b.HasIndex("UserGroupsId");

                    b.ToTable("User_GroupsMessage", (string)null);
                });

            modelBuilder.Entity("UserChatService.Domain.Entities.UserChat.UserGroupsMessageUserDeleted", b =>
                {
                    b.Property<long>("UserGroupsId")
                        .HasColumnType("bigint");

                    b.Property<long>("ToUserId")
                        .HasColumnType("bigint");

                    b.Property<long>("UserGroupsMessageId")
                        .HasColumnType("bigint");

                    b.HasKey("UserGroupsId", "ToUserId", "UserGroupsMessageId");

                    b.HasIndex("UserGroupsId", "ToUserId", "UserGroupsMessageId")
                        .IsUnique();

                    b.ToTable("User_GroupsMessageUserDeleted", (string)null);
                });

            modelBuilder.Entity("UserChatService.Domain.Entities.UserChat.UserGroupsMessageUserUnread", b =>
                {
                    b.Property<long>("UserGroupsId")
                        .HasColumnType("bigint");

                    b.Property<long>("ToUserId")
                        .HasColumnType("bigint");

                    b.Property<long>("UserGroupsMessageId")
                        .HasColumnType("bigint");

                    b.HasKey("UserGroupsId", "ToUserId", "UserGroupsMessageId");

                    b.HasIndex("UserGroupsId", "ToUserId", "UserGroupsMessageId")
                        .IsUnique();

                    b.ToTable("User_GroupsMessageUserUnread", (string)null);
                });

            modelBuilder.Entity("UserChatService.Domain.Entities.UserChat.UserGroupsToUser", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("DeletionTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("TopTime")
                        .HasColumnType("datetime(6)");

                    b.Property<long>("UserGroupsId")
                        .HasColumnType("bigint");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.Property<string>("UserNameWithInGroups")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("UserGroupsId");

                    b.HasIndex("UserId", "UserGroupsId");

                    b.ToTable("User_GroupsToUser", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
