#See https://aka.ms/customizecontainer to learn how to customize your debug container and how Visual Studio uses this Dockerfile to build your images for faster debugging.

FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS base
USER app
WORKDIR /app

FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
ARG BUILD_CONFIGURATION=Release
WORKDIR /src
COPY ["YouShowService.WebAPI/YouShowService.WebAPI.csproj", "YouShowService.WebAPI/"]
COPY ["CommonInitializer/CommonInitializer.csproj", "CommonInitializer/"]
COPY ["Chen.ASPNETCore/Chen.ASPNETCore.csproj", "Chen.ASPNETCore/"]
COPY ["Chen.Commons/Chen.Commons.csproj", "Chen.Commons/"]
COPY ["Chen.EventBus/Chen.EventBus.csproj", "Chen.EventBus/"]
COPY ["Chen.Infrastructure/Chen.Infrastructure.csproj", "Chen.Infrastructure/"]
COPY ["Chen.DomainCommons/Chen.DomainCommons.csproj", "Chen.DomainCommons/"]
COPY ["Chen.JWT/Chen.JWT.csproj", "Chen.JWT/"]
COPY ["YouShowService.Domain/YouShowService.Domain.csproj", "YouShowService.Domain/"]
COPY ["YouShowService.Infrastructure/YouShowService.Infrastructure.csproj", "YouShowService.Infrastructure/"]
COPY ["FileService.SDK.NETCore/FileService.SDK.NETCore.csproj", "FileService.SDK.NETCore/"]
RUN dotnet restore "./YouShowService.WebAPI/YouShowService.WebAPI.csproj"
COPY . .
WORKDIR "/src/YouShowService.WebAPI"
RUN dotnet build "./YouShowService.WebAPI.csproj" -c $BUILD_CONFIGURATION -o /app/build

FROM build AS publish
ARG BUILD_CONFIGURATION=Release
RUN dotnet publish "./YouShowService.WebAPI.csproj" -c $BUILD_CONFIGURATION -o /app/publish /p:UseAppHost=false

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
# 在 ENTRYPOINT 中添加等待时间的命令
ENTRYPOINT ["sh", "-c", "sleep 5 && dotnet YouShowService.WebAPI.dll"]